repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12.10
  - repo: local
    hooks:
      - id: check-conflicts
        name: Check database conflicts
        entry: python src/scripts/check_conflicts.py --precommit
        language: system
        pass_filenames: false
        files: ^dictionary/.*\.db$
