repos:
  - repo: local
    hooks:
      - id: check-conflicts
        name: Check translation conflicts
        entry: python scripts/check_conflicts.py --precommit
        language: system
        pass_filenames: false
        always_run: true
