repos:
  - repo: local
    hooks:
      - id: check-conflicts
        name: Check translation conflicts
        entry: python src/scripts/check_conflicts.py --precommit
        language: system
        pass_filenames: false
        files: ^dictionary/.*\.db$
